name: Generate Snake Alternative

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: 

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Generate Snake with Random Movement
        uses: Platane/snk@master
        with:
          github_user_name: DPoveaa
          outputs: dist/snake.svg
          snake_color: random
          snake_outline: true

      - name: Commit and push
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add dist/snake.svg
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update snake animation - $(date)"
            git push
          fi
