name: Generate Snake

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@master
        with:
          github_user_name: DPoveaa
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
